default-private-join-message: "Hi %player%, Welcome back!"
admin-private-join-message: "Hi %player%, Welcome back!"
mod-private-join-message: "Hi %player%, Welcome back!"
vip-private-join-message: "Hi %player%, Welcome back!"
default-global-join-message: "[+] %player%"
admin-global-join-message: ""
mod-global-join-message: "[+] %player%"
vip-global-join-message: "[+] %player%"
default-global-quit-message: "[-] %player%"
admin-global-quit-message: ""
mod-global-quit-message: "[-] %player%"
vip-global-quit-message: "[-] %player%"