name: WelcomeTitles
main: com.xiluiis.WelcomeTitles
author: xShadowsystem
description: A simple Minecraft plugin that displays a customizable welcome title and chat message to players when they join the server.
version: 1.0.0-beta
api-version: 1.20
commands:
  welcometitles:
    description: test
    usage: test
permissions:
  welcometitles.default:
    description: Messages for default players.
    default: true
  welcometitles.admin:
    description: Messages for admin players.
    default: false
  welcometitles.mod:
    description: Messages for mod players.
    default: false
  welcometitles.vip:
    description: Messages for vip players.
    default: false